### ISSUE TITLE
Race condition ?

### ISSUE THREAD

**Issue by samxplogs** [cool4uma/UART_Terminal#1]
Thanks for the development. However, I have a problem with sending command during login.
To test it I have enabled serial on raspberrypi.

Raspberrypi didn't get the **pi** login as per /var/log/auth.log output

Jan  7 19:49:57 legacypi login[723]: pam_unix(login:auth): authentication failure; logname=LOGIN uid=0 euid=0 tty=/dev/ttyAMA0 ruser= rhost=
Jan  7 19:50:00 legacypi login[723]: FAILED LOGIN (1) on '/dev/ttyAMA0' FOR 'UNKNOWN', Authentication failure

https://user-images.githubusercontent.com/121982000/211169812-a502e87b-7e1b-4c51-b40f-bb57738ec114.MOV

**Comment by cool4uma** [comment]
The code is still very raw, posted so hastily because of the requests of the guys from the community.
So far, I've only tested it on routers with OpenWrt firmware. I continue to work on this app and will upload fixes soon.
Thank you for your interest.

**Comment by cool4uma** [comment]
Look at here: https://forums.gentoo.org/viewtopic-p-6531397.html
