### ISSUE TITLE
Feature Request: Keep view scrolled to end

### ISSUE THREAD

**Issue by crazypill** [cool4uma/UART_Terminal#13]
It would be cool if new input from the UART would display the new text instead of jumping back to the top of the text.  I have to constantly scroll down to see new text and each time it takes longer to scroll down so I usually quit the app and relaunch it.

**Comment by cool4uma** [comment]
@crazypill Thank you. I think it will be useful, so in today's commit I added this feature.

**Comment by crazypill** [comment]
Thank you for adding this!
