### ISSUE TITLE
Feature Request: Add more Baud Rates

### ISSUE THREAD

**Issue by ethzero** [cool4uma/UART_Terminal#15]
Hi [cool4uma],
Found myself out of luck today with my new Flipper Zero when trying to connect to a HI-LINK HLK-LD2410 24Ghz Human Presence Body Radar sensor as it has a no-so-common baud rate of 256,000.

FWIW, on the following Wiki page there's a list of "Common serial port speeds". It might be worth implement the full list as the Flipper Zero it going to be used for all manner of common & odd devices!
https://en.wikipedia.org/wiki/Serial_port#Settings

Thanks,
-ethzero

**Comment by cool4uma** [comment]
Hello!
This is a good idea. In the next commit, I will include the entire list of speeds.
Thank you.

**Comment by cool4uma** [comment]
Done

**Comment by cool4uma** [comment]
Done
