### ISSUE TITLE
Missing include on uart_text_input.c

### ISSUE THREAD

**Issue by aafksab** [cool4uma/UART_Terminal#5]
#include "uart_terminal_icons.h"

I cannot locate this file in the project
cannot compile

**Comment by cool4uma** [comment]
this file is generated on the fly by fbt or ufbt tools.
I just cloned the repository and tried to build with both tools and it works for me.

**Comment by cool4uma** [comment]
you build with ufbt tool?

**Comment by aafksab** [comment]
I used fbt

**Comment by aafksab** [comment]
ok I can now build, ty
