### ISSUE TITLE
AT commands

### ISSUE THREAD

**Issue by qqmajikpp** [cool4uma/UART_Terminal#7]
the LORA module expects commands to be in all caps. sending:
at
gets response
+ERR=1

i should be able to send:
AT
which would respond with:
+OK

**Comment by qqmajikpp** [comment]
i figured out a long press does caps. AT+BAND? replies back with 915000000
but AT+ADDRESS? replies back with +ERR=1

**Comment by cool4uma** [comment]
![hc1e](https://user-images.githubusercontent.com/122148894/229546704-6aa1524a-e670-417a-b724-06ed0a4d0177.jpg)
![hc2](https://user-images.githubusercontent.com/122148894/229546725-f7290aab-67a7-4fa3-b0cd-06270102f923.jpg)
![hc3](https://user-images.githubusercontent.com/122148894/229546767-0a1586f2-4502-49c3-bb83-a04a60a589e8.jpg)

**Comment by qqmajikpp** [comment]
#
![20230403_105504](https://user-images.githubusercontent.com/84942886/229547712-c896a152-fb50-4549-8fe9-8f2e8bc383bb.jpg)
![20230403_105500](https://user-images.githubusercontent.com/84942886/229547745-14526193-25b7-4e6a-89fe-8367e6c32c65.jpg)

**Comment by cool4uma** [comment]
Yesterday there was a new commit where I added support for AT commands. Did you update UART_terminal?

**Comment by qqmajikpp** [comment]
> Yesterday there was a new commit where I added support for AT commands. Did you update UART_terminal?

![Uploading 20230403_105645.jpg…]()

**Comment by qqmajikpp** [comment]
![20230403_105645](https://user-images.githubusercontent.com/84942886/229548330-d9fad247-9484-4e6d-b0e8-3f10a4370cb1.jpg)

**Comment by cool4uma** [comment]
Ok. I'll test some more later and write to you.

**Comment by cool4uma** [comment]
try this command : AT+DADDR

**Comment by cool4uma** [comment]
@qqmajikpp You can re-pull and rebuild? Test and give me feedback please.
Ok?

**Comment by qqmajikpp** [comment]
I can query band but I still can't query address
![20230404_071414](https://user-images.githubusercontent.com/84942886/229775331-2979ceab-80cc-499b-a990-1c6b5da32008.jpg)
![20230404_071421](https://user-images.githubusercontent.com/84942886/229775335-2982cf6f-c66d-42b4-9181-2e76898a0ef8.jpg)
![20230404_071451](https://user-images.githubusercontent.com/84942886/229775341-cdb4bebb-478f-44f2-b4c8-d922ad265db1.jpg)
![20230404_071457](https://user-images.githubusercontent.com/84942886/229775345-943f3a5b-aa42-4ba2-a740-670266d61fa2.jpg)

**Comment by cool4uma** [comment]
Yes, I  read the documentation for this error.
I tested on different modules that are controlled by AT commands and these modules also require "\r \n", but I have not seen such an error or other problems.
Apparently I will have to buy a LoRa module to deal with this error.

**Comment by cool4uma** [comment]
@aafksab @qqmajikpp 
Can you show the output of these commands "AT+PARAMETER?" and "AT+ADDRESS?"? For example, from a computer, where do these commands work normally?

**Comment by aafksab** [comment]
![image](https://user-images.githubusercontent.com/36931057/229900613-2e9a7f59-986b-457a-a735-7aba06c515f5.png)

**Comment by cool4uma** [comment]
https://www.youtube.com/watch?v=C8DKtFBkQ60
Have you watched this video? Here everything works fine for the author?
